---
- name: Create users 
  hosts: all
  become: true
  vars_files:
    - user_list.yml
    - vars/secrets.yml
  
  tasks:
    
    - name: Creando los usuarios dev.
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        password: "{{ dev_pass | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"
      when: "'dev' in group_names and item['job']  == 'manager'" 