---
- name: Create users 
  hosts: dev
  become: true
  vars:
    users:
      - username: joe
        userpass: passjoe
      - username: sam
        userpass: passsam
  tasks:
    - name: Creando los usuarios joe y sam.
      ansible.builtin.user:
        name: "{{ item['username'] }}"
        state: present
      loop: "{{ users }}"